accelerator: gpu
checkpoint: null
data:
  binning_args:
    num_bins: 50
    num_knots: 50
    phi1_max: 12
    phi1_min: -20
  binning_fn: bin_stream_spline
  features:
  - phi1
  - phi2
  - pm1
  - pm2
  - vr
  - dist
  frac: true
  labels:
  - log_M_sat
  - log_rs_sat
  - vz
  - vphi
  - r
  - phi
  name: 6params-aau
  name_processed: 6params-aau-spline-sf20
  num_datasets: 90
  num_subsamples: 1
  root: /pscratch/sd/t/tvnguyen/stream_sbi_shared/datasets
  root_processed: /pscratch/sd/t/tvnguyen/stream_sbi_shared/datasets
  subsample_factor: 20
enable_progress_bar: false
eval_batch_size: 64
featurizer:
  activation:
    name: Identity
  batch_first: true
  d_feat: 128
  d_feat_in: 13
  d_time: 128
  d_time_in: 1
  dim_feedforward: 256
  name: transformer
  nhead: 4
  num_encoder_layers: 4
flows:
  activation:
    name: gelu
  hidden_sizes:
  - 256
  - 256
  - 256
  - 256
  num_bins: 8
  num_transforms: 4
  zuko: true
grad_clip: 0.5
mlp:
  activation:
    name: gelu
  batch_norm: true
  dropout: 0.1
  hidden_sizes:
  - 256
  - 256
mode: min
monitor: val_loss
name: 6params-aau-spline
num_steps: 500000
num_workers: 0
optimizer:
  betas: !!python/tuple
  - 0.9
  - 0.98
  eps: 1.0e-09
  lr: 0.0005
  name: AdamW
  weight_decay: 0.0001
output_size: 6
overwrite: false
patience: 10000
save_top_k: 5
scheduler:
  decay_steps: 500000
  eta_min: 0.01
  interval: step
  name: WarmUpCosineAnnealingLR
  warmup_steps: 50000
seed_data: 10
seed_training: 20
train_batch_size: 64
train_frac: 0.8
workdir: /pscratch/sd/t/tvnguyen/stream_sbi_shared/trained-models
